[package]
name = "machine-check-macros"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Macro crate for the formal verification tool machine-check"
rust-version = "1.70"
type = "proc-macro"

[dependencies]
