[workspace]

resolver = "2"
members = [
    "mck",
    "mck-macro",
    "machine-check-lib",
    "machine-check",
    "machine-check-exec",
    "machine-check-batch",
    "btor2rs",
    "btor2rs-bin",
]
