[workspace]

resolver = "2"
members = ["core/*", "support/*"]

[patch.crates-io]
btor2rs = { path = "./core/btor2rs" }
machine-check-common = { path = "./core/machine-check-common" }
mck = { path = "./core/mck" }
machine-check = { path = "./core/machine-check" }
machine-check-exec = { path = "./core/machine-check-exec" }
