[workspace]

resolver = "2"
members = [
    "mck",
    "machine-check-lib",
    "machine-check",
    "machine-check-exec",
    "machine-check-exec-target",
    "machine-check-exec-prepare",
    "machine-check-batch",
    "btor2rs",
]
