[package]
name = "machine-check-exec"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
mck = { path = "../mck" }
mck-macro = { path = "../mck-macro" }
machine-check-exec-lib = { path = "../machine-check-exec-lib" }
