[package]
name = "machine-check-exec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mck = { path = "../mck" }
anyhow = "1.0.75"
bimap = "0.6.3"
petgraph = "0.6.4"
