[package]
name = "machine-check-riscv"

description = "System crate for machine-check for verification of RISCV microcontrollers"
homepage = "https://machine-check.org/"
repository = "https://github.com/onderjan/machine-check"
license = "MIT OR Apache-2.0"
readme = "README.md"

edition = "2021"
rust-version = "1.88"
#version = "0.7.0"

[features]
gui = ["machine-check/gui"]
Zdual_interval = ["machine-check/Zdual_interval"]
Zeq_domain = ["machine-check/Zeq_domain"]

[dependencies]
machine-check = "=0.7.0"

proc-macro2 = "1.0.67"
quote = "1.0.28"
syn = "2.0.37"
anyhow = "1.0.100"

object = "0.37.3"
gimli = { version = "0.32.3", default-features = false, features = [
    "std",
    "read",
] }

clap = { version = "4.4.6", features = ["derive"] }

log = "0.4.20"


[lints.clippy]
uninlined_format_args = "allow"
