[package]
name = "machine-check-common"
version = "0.7.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Utility crate for the formal verification tool machine-check"
rust-version = "1.88"

[dependencies]
mck = "=0.7.0-alpha.1"

thiserror = "1.0.49"
serde = { version = "1.0.228", features = ["derive", "rc"] }
proc-macro2 = "1.0.67"
strum = { version = "0.27", features = ["derive"] }
indexmap = { version = "2.12.0", features = ["serde"] }

[lints.clippy]
uninlined_format_args = "allow"
