[package]
name = "machine-check-common"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0.49"
serde = { version = "1.0.188", features = ["derive"] }
