[package]
name = "machine-check-common"

description = "Utility crate for the formal verification tool machine-check"
homepage = "https://machine-check.org/"
repository = "https://github.com/onderjan/machine-check"
license = "MIT OR Apache-2.0"
readme = "README.md"

edition = "2021"
rust-version = "1.88"
version = "0.7.0-alpha.4"

[dependencies]
mck = "=0.7.0-alpha.4"

thiserror = "1.0.49"
serde = { version = "1.0.228", features = ["derive", "rc"] }
proc-macro2 = "1.0.67"
strum = { version = "0.27", features = ["derive"] }
indexmap = { version = "2.12.0", features = ["serde"] }

[lints.clippy]
uninlined_format_args = "allow"
