[package]
name = "btor2rs"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Safe-Rust Btor2 parser"
rust-version = "1.70"

[dependencies]
thiserror = "1.0.49"
strum = { version = "0.25", features = ["derive"] }
