[package]
name = "machine-check-types"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Type/operation utility crate for the formal verification tool machine-check"
rust-version = "1.75"

[dependencies]
mck = "=0.1.0"
