[package]
name = "btor2rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.75"
proc-macro2 = "1.0.67"
quote = "1.0.33"
strum = { version = "0.25", features = ["derive"] }
