[package]
name = "machine-check-avr"

description = "System crate for machine-check for verification of AVR microcontrollers"
homepage = "https://machine-check.org/"
repository = "https://github.com/onderjan/machine-check"
license = "MIT OR Apache-2.0"
readme = "README.md"

edition = "2021"
rust-version = "1.88"
version = "0.7.0-alpha.5"

[features]
gui = ["machine-check/gui"]
Zdual_interval = ["machine-check/Zdual_interval"]
Zeq_domain = ["machine-check/Zeq_domain"]

[dependencies]
machine-check = "=0.7.0-alpha.5"

ihex = "3.0.0"
clap = { version = "4.4.6", features = ["derive"] }
pastey = "0.1.0"

[lints.clippy]
uninlined_format_args = "allow"
