[package]
name = "mck"

description = "Utility crate for the formal verification tool machine-check"
homepage = "https://machine-check.org/"
repository = "https://github.com/onderjan/machine-check"
license = "MIT OR Apache-2.0"
readme = "README.md"

edition = "2021"
rust-version = "1.88"
version = "0.7.0-alpha.2"

[features]
Zdual_interval = []
Zeq_domain = []

#default = ["Zdual_interval"]
#default = ["Zeq_domain"]
#default = ["Zdual_interval", "Zeq_domain"]

[dependencies]
seq-macro = "0.3.5"
num = "0.4.3"

serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.145"

[lints.clippy]
uninlined_format_args = "allow"
