[package]
name = "btor2rs-bin"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
btor2rs = { path = "../btor2rs" }
anyhow = "1.0.75"
proc-macro2 = "1.0.67"
prettyplease = "0.2.15"
syn = "2.0.37"
walkdir = "2.4.0"
