[package]
name = "machine-check-exec-prepare"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cargo_metadata = "0.18.0"
serde = "1.0.188"
serde_json = "1.0.107"
walkdir = "2.4.0"
