[package]
name = "machine-check"
version = "0.1.0"
edition = "2021"

[dependencies]
machine-check-traits = { path = "../machine-check-traits" }
machine-check-macros = { path = "../machine-check-macros" }
num = "0.4.0"
