[package]
name = "machine-check-exec"
version = "0.3.1-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Utility crate for the formal verification tool machine-check"
rust-version = "1.75"

[dependencies]
mck = "=0.3.0"
machine-check-common = "=0.3.0"

thiserror = "1.0.49"
anyhow = "1.0.75"
bimap = "0.6.3"
petgraph = "0.6.4"
clap = { version = "4.4.6", features = ["derive"] }
log = "0.4.20"
env_logger = "0.10.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
