[package]
name = "machine-check-exec"
version = "0.3.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Utility crate for the formal verification tool machine-check"
rust-version = "1.75"

[dependencies]
mck = "=0.3.1"
machine-check-common = "=0.3.1"

bimap = "0.6.3"
petgraph = "0.6.4"
log = "0.4.20"
