[package]
name = "machine-check-exec-target"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
mck = { path = "../mck" }
machine-check-exec = { path = "../machine-check-exec" }
