[package]
name = "machine-check-exec-prepare"
version = "0.5.0-alpha.2"
edition = "2021"
rust-version = "1.83"
# internal artifact, do not publish
publish = false

[dependencies]
mck = "=0.5.0-alpha.2"
machine-check = "=0.5.0-alpha.2"
machine-check-exec = "=0.5.0-alpha.2"

[workspace]
# disallow workspace hijinks
