[package]
name = "machine-check-exec-prepare"
version = "0.6.0"
edition = "2021"
rust-version = "1.83"
# internal artifact, do not publish
publish = false

[features]
gui = ["machine-check/gui"]
Zdual_interval = ["machine-check/Zdual_interval"]

[dependencies]
mck = "=0.6.0"
machine-check = "=0.6.0"
machine-check-exec = "=0.6.0"

[workspace]
# disallow workspace hijinks
