[package]
name = "machine-check-exec-prepare"
version = "0.3.1-alpha-1"
edition = "2021"
rust-version = "1.83"
# internal artifact, do not publish
publish = false

[dependencies]
mck = "=0.3.1"
machine-check = "=0.3.1"
machine-check-exec = "=0.3.1"

[workspace]
# disallow workspace hijinks
