[package]
name = "machine-check-exec-target"
version = "0.2.0-alpha.2"
edition = "2021"
rust-version = "1.75"
# internal artifact, do not publish
publish = false

[dependencies]
mck = "=0.2.0-alpha.2"
machine-check = "=0.2.0-alpha.2"
machine-check-exec = "=0.2.0-alpha.2"

[workspace]
# disallow workspace hijinks
