[package]
name = "machine-check-exec-lib"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
mck = { path = "../mck" }
thiserror = "1.0.49"
bimap = "0.6.3"
petgraph = "0.6.4"
clap = { version = "4.4.6", features = ["derive"] }
