[package]
name = "machine-check"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Formal verification tool for digital systems"
rust-version = "1.75"

[dependencies]
mck = "=0.1.0"
machine-check-macros = "=0.1.0"

[dev-dependencies]
machine-check-exec = "=0.1.0"
