[package]
name = "machine-check"
version = "0.6.1-alpha.2"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Formal verification tool for digital systems"
rust-version = "1.83"

[features]
gui = ["machine-check-gui"]
Zdual_interval = ["mck/Zdual_interval"]

[dependencies]
machine-check-common = "=0.6.1-alpha.2"
mck = "=0.6.1-alpha.2"
machine-check-macros = "=0.6.1-alpha.2"
machine-check-exec = "=0.6.1-alpha.2"
machine-check-gui = { version = "=0.6.1-alpha.2", optional = true }

log = "0.4.20"
env_logger = "0.10.0"
clap = { version = "4.4.6", features = ["derive"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"

[dev-dependencies]
trybuild = "1.0.105"
escargot = "0.5.15"

# These examples must be explicitely specified
# as Cargo does not by default consider nested examples
# except for those in subfolders with name main.rs.
# 
# We use them to test the examples in the book.

[[example]]
name = "book_quickstart"
path = "examples/book/book_quickstart.rs"

[[example]]
name = "book_instances_input"
path = "examples/book/book_instances_input.rs"

[[example]]
name = "book_instances_todo"
path = "examples/book/book_instances_todo.rs"

# Miscellaneous examples with use as tests.

[[example]]
name = "misc_freerun"
path = "examples/misc/freerun.rs"
